.TH "JSON\-DOC" "1" "August 2013" "" ""
.SH "NAME"
\fBjson-doc\fR \- document a JSON file with a JSON schema
.SH SYNOPSIS
.P
json\-doc source schema
.SH DESCRIPTION
.P
\fBjson\-doc\fR is a command line tool that will take a source JSON file and a JSON
schema file and generate a static page like http://package\.json\.nodejitsu\.com\|\.
.P
\fBsource\fR \- This is the source JSON file that you want to document\.
.P
\fBschema\fR \- This is the json\-schema\.org syntax file\.
.SH SEE ALSO
.P
http://json\-schema\.org
.P
http://jsonschema\.net
.SH AUTHOR
.P
James Young jmeyoung@gmail\.com http://jamsyoung\.com

